name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          # 💡 修改 1：將 jsBrowserDistribution 改為 wasmJsBrowserDistribution
          ./gradlew clean :webApp:wasmJsBrowserDistribution --no-daemon --no-configuration-cache --no-build-cache --stacktrace -Pkotlin.incremental=false

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 💡 修改 2：將輸出資料夾的 js 改為 wasmJs
          folder: webApp/build/dist/wasmJs/productionExecutable
          branch: gh-pages
